import configparser
import os

class AsetManager:
    """
    Manages loading and saving to Artisan-compatible .aset files.
    .aset files are effectively INI files generated by Qt's QSettings module.
    """
    
    def __init__(self, default_file="Raga_JOSS_wirles.aset"):
        self.filename = default_file
        self.config = configparser.ConfigParser(strict=False)
        self.config.optionxform = str  # Preserve case sensitivity (crucial for Artisan)
        
        # Default fallback values for ModBus TCP if file doesn't exist
        self.default_config = {
            'comport': '192.168.11.3', # Artisan uses socket://IP:PORT for TCP, but we'll store basic IP
            'baudrate': '9600',
            'modbustype': '1', # 1 generally implies TCP in Artisan's raw index
            'modbusport': '5000',
            # ET Config (Input 1)
            'input1deviceId': '1',
            'input1register': '1000',
            'input1code': '4',
            # BT Config (Input 2)
            'input2deviceId': '2',
            'input2register': '1000',
            'input2code': '4'
        }
        
    def load_config(self):
        """Loads an existing .aset file, or returns defaults if none exists."""
        if os.path.exists(self.filename):
            try:
                # Artisan .aset uses standard INI sections, often root or [General]
                self.config.read(self.filename)
                
                # We extract specifically what we need. Artisan dumps hundreds of Qt keys.
                # Assuming they are placed in root or a specific section.
                # Since .aset structure can be flat or sectioned, we flatten our read logic.
                
                extracted = {}
                for section in self.config.sections():
                    for key, val in self.config.items(section):
                        extracted[key] = val.replace('@Variant(', '').strip(')\'"')
                
                # Merge extracted over defaults
                current_config = self.default_config.copy()
                for k in current_config.keys():
                    if k in extracted:
                        current_config[k] = extracted[k]
                        
                # Handle special case: Artisan socket URL parsing
                import re
                if 'socket://' in current_config.get('comport', ''):
                    match = re.search(r'socket://(.*?):(\d+)', current_config['comport'])
                    if match:
                        current_config['comport'] = match.group(1)
                        current_config['modbusport'] = match.group(2)
                        
                return current_config
            except Exception as e:
                print(f"Failed to read .aset: {e}")
                return self.default_config
        else:
            return self.default_config

    def save_config(self, modified_dict):
        """Saves dictionary back into the .aset INI format."""
        
        # If file exists, read it first so we don't destroy other Artisan settings
        if os.path.exists(self.filename):
            self.config.read(self.filename)
        
        if not self.config.has_section('General'):
            self.config.add_section('General')
            
        for key, value in modified_dict.items():
            # Apply Artisan-like QVariant typing if needed (simplified for text)
            self.config.set('General', key, str(value))
            
        try:
            with open(self.filename, 'w') as configfile:
                self.config.write(configfile)
            return True
        except Exception as e:
            print(f"Error writing to .aset: {e}")
            return False
